change to use kwargs instead of specific named arguments.
Running this on the whole set of files (few thousand) runs into database
lock exceptions.

OperationalError: (sqlite3.OperationalError) database is locked